"""Add product and cargo models

Revision ID: 05baf68752c6
Revises: 6c3bb5771347
Create Date: 2026-03-17 15:16:57.403662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05baf68752c6'
down_revision: Union[str, Sequence[str], None] = '6c3bb5771347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('cargo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'cargos', ['cargo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contacts', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'cargo_id')
    op.drop_column('contacts', 'product_id')
    # ### end Alembic commands ###
