"""Add and modify fields in Empresa model

Revision ID: 1b0c15b12028
Revises: 8cb0ed89594f
Create Date: 2026-04-07 16:22:20.156825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0c15b12028'
down_revision: Union[str, Sequence[str], None] = '8cb0ed89594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.add_column('empresas', sa.Column('sector', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('vertical', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('producto', sa.String(length=255), nullable=True))
    op.alter_column('empresas', 'ingresos_totales',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresas', 'ingresos_totales',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('empresas', 'producto')
    op.drop_column('empresas', 'vertical')
    op.drop_column('empresas', 'sector')
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('settings_pkey'))
    )
    # ### end Alembic commands ###
