"""add_competitor_and_social_fields_to_empresa

Revision ID: 72477b692ea5
Revises: db1a857b13ad
Create Date: 2026-04-30 15:12:19.244499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72477b692ea5'
down_revision: Union[str, Sequence[str], None] = 'db1a857b13ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.add_column('empresas', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('web_competidor_1', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('web_competidor_2', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('web_competidor_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'web_competidor_3')
    op.drop_column('empresas', 'web_competidor_2')
    op.drop_column('empresas', 'web_competidor_1')
    op.drop_column('empresas', 'facebook')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    # ### end Alembic commands ###
