"""case_insensitive_unique_tags

Revision ID: 515c73b61450
Revises: 007_event_system
Create Date: 2026-04-20 16:13:34.932539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '515c73b61450'
down_revision: Union[str, Sequence[str], None] = '007_event_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM campaigns a USING campaigns b WHERE lower(a.nombre) = lower(b.nombre) AND a.id > b.id;"))
    conn.execute(sa.text("DELETE FROM products a USING products b WHERE lower(a.name) = lower(b.name) AND a.id > b.id;"))
    conn.execute(sa.text("DELETE FROM sectors a USING sectors b WHERE lower(a.name) = lower(b.name) AND a.id > b.id;"))
    conn.execute(sa.text("DELETE FROM verticals a USING verticals b WHERE lower(a.name) = lower(b.name) AND a.id > b.id;"))
    
    op.drop_constraint(op.f('campaigns_nombre_key'), 'campaigns', type_='unique')
    op.create_index('ix_campaigns_nombre_lower', 'campaigns', [sa.literal_column("lower('nombre')")], unique=True)
    
    op.drop_constraint(op.f('cargos_name_key'), 'cargos', type_='unique')
    
    op.drop_constraint(op.f('products_name_key'), 'products', type_='unique')
    op.create_index('ix_products_name_lower', 'products', [sa.literal_column("lower('name')")], unique=True)
    
    op.drop_constraint(op.f('sectors_name_key'), 'sectors', type_='unique')
    op.create_index('ix_sectors_name_lower', 'sectors', [sa.literal_column("lower('name')")], unique=True)
    
    op.drop_constraint(op.f('verticals_name_key'), 'verticals', type_='unique')
    op.create_index('ix_verticals_name_lower', 'verticals', [sa.literal_column("lower('name')")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verticals_name_lower', table_name='verticals')
    op.create_unique_constraint(op.f('verticals_name_key'), 'verticals', ['name'], postgresql_nulls_not_distinct=False)
    
    op.drop_index('ix_sectors_name_lower', table_name='sectors')
    op.create_unique_constraint(op.f('sectors_name_key'), 'sectors', ['name'], postgresql_nulls_not_distinct=False)
    
    op.drop_index('ix_products_name_lower', table_name='products')
    op.create_unique_constraint(op.f('products_name_key'), 'products', ['name'], postgresql_nulls_not_distinct=False)
    
    op.create_unique_constraint(op.f('cargos_name_key'), 'cargos', ['name'], postgresql_nulls_not_distinct=False)
    
    op.drop_index('ix_campaigns_nombre_lower', table_name='campaigns')
    op.create_unique_constraint(op.f('campaigns_nombre_key'), 'campaigns', ['nombre'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
