"""fix_unique_indices_functional

Revision ID: 279e8598329b
Revises: a07faa59cd15
Create Date: 2026-04-23 10:24:55.437722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '279e8598329b'
down_revision: Union[str, Sequence[str], None] = 'a07faa59cd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargos', 'normalized_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('cargos_normalized_name_key'), 'cargos', type_='unique')
    op.create_index(op.f('ix_cargos_normalized_name'), 'cargos', ['normalized_name'], unique=True)
    op.drop_column('contacts', 'products')
    op.drop_index(op.f('ix_empresas_nombre_lower'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=True)
    op.drop_index(op.f('idx_enrichment_logs_tool_created'), table_name='enrichment_logs')
    op.alter_column('logs', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único del registro de log',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID del usuario que ejecutó la acción (NULL si anónimo)',
               existing_nullable=True)
    op.alter_column('logs', 'action',
               existing_type=sa.TEXT(),
               comment='Descripción de la acción realizada',
               existing_nullable=False)
    op.alter_column('logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Datos adicionales de la acción en formato JSONB',
               existing_nullable=True)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora del registro de la acción',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_requests', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único de la solicitud',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_requests', 'email',
               existing_type=sa.TEXT(),
               comment='Email del usuario que solicita acceso',
               existing_nullable=False)
    op.alter_column('user_requests', 'password',
               existing_type=sa.TEXT(),
               comment='Hash bcrypt de la contraseña del solicitante',
               existing_nullable=False)
    op.alter_column('user_requests', 'status',
               existing_type=sa.TEXT(),
               comment='Estado: pending, approved o rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('user_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creación de la solicitud',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_requests', 'reviewed_by',
               existing_type=sa.INTEGER(),
               comment='ID del admin que revisó (NULL si pendiente)',
               existing_nullable=True)
    op.alter_column('user_requests', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de la revisión (NULL si pendiente)',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único del usuario',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email único del usuario (se usa para login)',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash bcrypt de la contraseña',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               comment="Rol del usuario: 'admin' o 'gestor'",
               existing_nullable=False,
               existing_server_default=sa.text("'gestor'::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creación del usuario',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='False = usuario eliminado lógicamente (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='False = usuario eliminado lógicamente (soft delete)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creación del usuario',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Rol del usuario: 'admin' o 'gestor'",
               existing_nullable=False,
               existing_server_default=sa.text("'gestor'::text"))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hash bcrypt de la contraseña',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email único del usuario (se usa para login)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único del usuario',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_requests', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de la revisión (NULL si pendiente)',
               existing_nullable=True)
    op.alter_column('user_requests', 'reviewed_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del admin que revisó (NULL si pendiente)',
               existing_nullable=True)
    op.alter_column('user_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creación de la solicitud',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_requests', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Estado: pending, approved o rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('user_requests', 'password',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Hash bcrypt de la contraseña del solicitante',
               existing_nullable=False)
    op.alter_column('user_requests', 'email',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Email del usuario que solicita acceso',
               existing_nullable=False)
    op.alter_column('user_requests', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único de la solicitud',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora del registro de la acción',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Datos adicionales de la acción en formato JSONB',
               existing_nullable=True)
    op.alter_column('logs', 'action',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descripción de la acción realizada',
               existing_nullable=False)
    op.alter_column('logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del usuario que ejecutó la acción (NULL si anónimo)',
               existing_nullable=True)
    op.alter_column('logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único del registro de log',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_enrichment_logs_tool_created'), 'enrichment_logs', ['tool', 'created_at'], unique=False)
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.create_index(op.f('ix_empresas_nombre_lower'), 'empresas', [sa.literal_column('lower(nombre::text)')], unique=True)
    op.add_column('contacts', sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cargos_normalized_name'), table_name='cargos')
    op.create_unique_constraint(op.f('cargos_normalized_name_key'), 'cargos', ['normalized_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('cargos', 'normalized_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
