"""add user_id to enrichment_logs

Revision ID: 5d48b634302f
Revises: 72477b692ea5
Create Date: 2026-05-06 17:16:44.313844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d48b634302f'
down_revision: Union[str, Sequence[str], None] = '72477b692ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrichment_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrichment_logs', 'user_id')
    # ### end Alembic commands ###
