"""Add linkedin_normalized

Revision ID: 3bb54436c3d7
Revises: 18eacb21e9e1
Create Date: 2026-04-19 13:10:07.761054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb54436c3d7'
down_revision: Union[str, Sequence[str], None] = '18eacb21e9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('linkedin_normalized', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_contacts_linkedin_normalized'), 'contacts', ['linkedin_normalized'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_linkedin_normalized'), table_name='contacts')
    op.drop_column('contacts', 'linkedin_normalized')
    # ### end Alembic commands ###
