"""Refactor to M2M

Revision ID: 2a48471ed734
Revises: 05baf68752c6
Create Date: 2026-03-18 12:36:22.589379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a48471ed734'
down_revision: Union[str, Sequence[str], None] = '05baf68752c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_cargos',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'cargo_id')
    )
    op.create_table('contact_products',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'product_id')
    )
    op.create_table('contact_sectors',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'sector_id')
    )
    op.create_table('contact_verticals',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'vertical_id')
    )
    
    # Data migration
    op.execute("INSERT INTO contact_cargos (contact_id, cargo_id) SELECT id, cargo_id FROM contacts WHERE cargo_id IS NOT NULL")
    op.execute("INSERT INTO contact_products (contact_id, product_id) SELECT id, product_id FROM contacts WHERE product_id IS NOT NULL")
    op.execute("INSERT INTO contact_sectors (contact_id, sector_id) SELECT id, sector_id FROM contacts WHERE sector_id IS NOT NULL")
    op.execute("INSERT INTO contact_verticals (contact_id, vertical_id) SELECT id, vertical_id FROM contacts WHERE vertical_id IS NOT NULL")

    op.drop_constraint(op.f('contacts_cargo_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_sector_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_vertical_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_product_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'cargo_id')
    op.drop_column('contacts', 'product_id')
    op.drop_column('contacts', 'sector_id')
    op.drop_column('contacts', 'vertical_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('vertical_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('cargo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('contacts_product_id_fkey'), 'contacts', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contacts_vertical_id_fkey'), 'contacts', 'verticals', ['vertical_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contacts_sector_id_fkey'), 'contacts', 'sectors', ['sector_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contacts_cargo_id_fkey'), 'contacts', 'cargos', ['cargo_id'], ['id'], ondelete='SET NULL')

    # Data migration downgrade
    op.execute("UPDATE contacts SET vertical_id = (SELECT vertical_id FROM contact_verticals WHERE contact_id = contacts.id LIMIT 1)")
    op.execute("UPDATE contacts SET sector_id = (SELECT sector_id FROM contact_sectors WHERE contact_id = contacts.id LIMIT 1)")
    op.execute("UPDATE contacts SET product_id = (SELECT product_id FROM contact_products WHERE contact_id = contacts.id LIMIT 1)")
    op.execute("UPDATE contacts SET cargo_id = (SELECT cargo_id FROM contact_cargos WHERE contact_id = contacts.id LIMIT 1)")

    op.drop_table('contact_verticals')
    op.drop_table('contact_sectors')
    op.drop_table('contact_products')
    op.drop_table('contact_cargos')
    # ### end Alembic commands ###
