"""Add score and revenue to contact

Revision ID: 71a0d25fbbc4
Revises: 8c620c969844
Create Date: 2026-03-18 17:42:53.442649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a0d25fbbc4'
down_revision: Union[str, Sequence[str], None] = '8c620c969844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.add_column('contacts', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('revenue', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'revenue')
    op.drop_column('contacts', 'score')
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('settings_pkey'))
    )
    # ### end Alembic commands ###
