"""Drop score revenue columns from contacts

Revision ID: c1891a272b29
Revises: 71a0d25fbbc4
Create Date: 2026-03-18 18:04:54.216133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1891a272b29'
down_revision: Union[str, Sequence[str], None] = '71a0d25fbbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_column('contacts', 'score')
    op.drop_column('contacts', 'revenue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('revenue', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('settings_pkey'))
    )
    # ### end Alembic commands ###
