"""make email_contact unique

Revision ID: 10d7fad11e98
Revises: e5743880c8ac
Create Date: 2026-04-14 11:49:59.957651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d7fad11e98'
down_revision: Union[str, Sequence[str], None] = 'e5743880c8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contacts', ['email_contact'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    # ### end Alembic commands ###
