"""baseline_from_scratch

Revision ID: e5743880c8ac
Revises: 
Create Date: 2026-04-13 15:34:49.994517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5743880c8ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('presupuesto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('objetivo', sa.String(length=500), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('canal', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cif', sa.String(length=50), nullable=True),
    sa.Column('numero_empleados', sa.Integer(), nullable=True),
    sa.Column('facturacion', sa.Float(), nullable=True),
    sa.Column('cnae', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=True)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único del registro de log'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ID del usuario que ejecutó la acción (NULL si anónimo)'),
    sa.Column('action', sa.Text(), nullable=False, comment='Descripción de la acción realizada'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Datos adicionales de la acción en formato JSONB'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora del registro de la acción'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_created_at', 'logs', ['created_at'], unique=False)
    op.create_index('idx_logs_user_id', 'logs', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único de la solicitud'),
    sa.Column('email', sa.Text(), nullable=False, comment='Email del usuario que solicita acceso'),
    sa.Column('password', sa.Text(), nullable=False, comment='Hash bcrypt de la contraseña del solicitante'),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False, comment='Estado: pending, approved o rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación de la solicitud'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='ID del admin que revisó (NULL si pendiente)'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de la revisión (NULL si pendiente)'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_user_requests_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID único del usuario'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email único del usuario (se usa para login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt de la contraseña'),
    sa.Column('role', sa.Text(), server_default='gestor', nullable=False, comment="Rol del usuario: 'admin' o 'gestor'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del usuario'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = usuario eliminado lógicamente (soft delete)'),
    sa.CheckConstraint("role IN ('admin', 'gestor')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verticals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('email_contact', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_products',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empresa_id', 'product_id')
    )
    op.create_table('empresa_sectors',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empresa_id', 'sector_id')
    )
    op.create_table('empresa_verticals',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empresa_id', 'vertical_id')
    )
    op.create_table('contact_campaigns',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'campaign_id')
    )
    op.create_table('contact_cargos',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'cargo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_cargos')
    op.drop_table('contact_campaigns')
    op.drop_table('empresa_verticals')
    op.drop_table('empresa_sectors')
    op.drop_table('empresa_products')
    op.drop_table('contacts')
    op.drop_table('verticals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_requests')
    op.drop_table('settings')
    op.drop_table('sectors')
    op.drop_table('products')
    op.drop_index('idx_logs_user_id', table_name='logs')
    op.drop_index('idx_logs_created_at', table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_table('cargos')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
