"""remove_company_column

Revision ID: 86d1b454f20f
Revises: 2a6246901e6f
Create Date: 2026-04-14 17:24:34.686110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d1b454f20f'
down_revision: Union[str, Sequence[str], None] = '2a6246901e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # Backfill missing empresas
    connection.execute(sa.text("""
        INSERT INTO empresas (nombre, created_at, updated_at)
        SELECT DISTINCT company, current_timestamp, current_timestamp
        FROM contacts 
        WHERE empresa_id IS NULL AND company IS NOT NULL 
          AND NOT EXISTS (SELECT 1 FROM empresas WHERE empresas.nombre = contacts.company)
    """))

    # Link contacts to empresas
    connection.execute(sa.text("""
        UPDATE contacts 
        SET empresa_id = empresas.id 
        FROM empresas 
        WHERE contacts.empresa_id IS NULL 
          AND contacts.company = empresas.nombre
    """))
    
    # Verify integrity
    result = connection.execute(sa.text("SELECT COUNT(*) FROM contacts WHERE empresa_id IS NULL AND company IS NOT NULL"))
    count = result.scalar()
    if count > 0:
        raise Exception(f"Migration aborted: {count} contacts still have no empresa_id assigned.")

    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE contacts 
        SET company = empresas.nombre 
        FROM empresas 
        WHERE contacts.empresa_id = empresas.id
    """))
    op.alter_column('contacts', 'company', nullable=False)
    # ### end Alembic commands ###
